openapi: "3.0.0"
info:
  title: FlowForge Formula Engine
  description: Excel-compatible formula evaluation with 118+ functions
  version: "1.0.0"
  contact:
    name: FlowForge Team

servers:
  - url: https://{instance}/api/v1/formula
    variables:
      instance:
        default: api.flowforge.io
        description: FlowForge instance URL

paths:
  /evaluate:
    post:
      operationId: EvaluateFormula
      summary: Evaluate a formula
      description: Evaluate an Excel-compatible formula with optional variables
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - formula
              properties:
                formula:
                  type: string
                  description: Formula to evaluate (e.g., "=SUM(A1:A10)" or "=IF(x>10, 'High', 'Low')")
                  maxLength: 10000
                variables:
                  type: object
                  description: Variable values to use in formula
                  additionalProperties: true
                context:
                  type: object
                  description: Cell context for relative references
                  properties:
                    row:
                      type: integer
                    col:
                      type: integer
      responses:
        "200":
          description: Formula evaluated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  result:
                    description: Evaluation result (can be number, string, boolean, or array)
                  type:
                    type: string
                    description: Result type
                    enum:
                      - number
                      - string
                      - boolean
                      - array
                      - error
                  formula:
                    type: string
                    description: Original formula

  /batch:
    post:
      operationId: BatchEvaluate
      summary: Evaluate multiple formulas
      description: Evaluate multiple formulas in a single request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - formulas
              properties:
                formulas:
                  type: array
                  description: List of formulas to evaluate
                  items:
                    type: object
                    required:
                      - formula
                    properties:
                      id:
                        type: string
                        description: Optional identifier for the formula
                      formula:
                        type: string
                      variables:
                        type: object
                        additionalProperties: true
                  minItems: 1
                  maxItems: 100
                shared_variables:
                  type: object
                  description: Variables shared across all formulas
                  additionalProperties: true
      responses:
        "200":
          description: Batch evaluation completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        formula:
                          type: string
                        result:
                          description: Evaluation result
                        success:
                          type: boolean
                        error:
                          type: string
                  total:
                    type: integer
                  succeeded:
                    type: integer
                  failed:
                    type: integer

  /validate:
    post:
      operationId: ValidateFormula
      summary: Validate formula syntax
      description: Check if a formula has valid syntax without evaluating it
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - formula
              properties:
                formula:
                  type: string
                  description: Formula to validate
                  maxLength: 10000
      responses:
        "200":
          description: Validation result
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  valid:
                    type: boolean
                    description: Whether the formula is syntactically valid
                  formula:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                        position:
                          type: integer
                  functions_used:
                    type: array
                    description: List of functions used in the formula
                    items:
                      type: string
                  variables_referenced:
                    type: array
                    description: List of variables referenced
                    items:
                      type: string

  /functions:
    get:
      operationId: ListFunctions
      summary: List available functions
      description: Get a list of all available formula functions
      parameters:
        - name: category
          in: query
          description: Filter by function category
          schema:
            type: string
            enum:
              - math
              - text
              - date
              - logical
              - lookup
              - statistical
              - financial
              - information
      responses:
        "200":
          description: List of available functions
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  functions:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        category:
                          type: string
                        description:
                          type: string
                        syntax:
                          type: string
                        examples:
                          type: array
                          items:
                            type: string
                  total:
                    type: integer

components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-API-Key
      description: FlowForge API Key

security:
  - ApiKey: []
