openapi: "3.0.0"
info:
  title: LeForge File Service
  description: Large file processing - upload, download, CSV/Excel processing, format conversion
  version: "1.0.0"
  contact:
    name: LeForge Team

servers:
  - url: https://{instance}/api/v1/files
    variables:
      instance:
        default: api.LeForge.io
        description: LeForge instance URL

paths:
  /upload:
    post:
      operationId: UploadFile
      summary: Upload a file
      description: Upload a file for processing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - filename
                - content
              properties:
                filename:
                  type: string
                  description: Name of the file
                  maxLength: 255
                content:
                  type: string
                  description: Base64-encoded file content
                content_type:
                  type: string
                  description: MIME type of the file
                  default: application/octet-stream
                metadata:
                  type: object
                  description: Optional metadata for the file
                  additionalProperties: true
      responses:
        "200":
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  file_id:
                    type: string
                    description: Unique identifier for the uploaded file
                  filename:
                    type: string
                  size:
                    type: integer
                    description: File size in bytes
                  content_type:
                    type: string

  /download:
    post:
      operationId: DownloadFile
      summary: Download a file
      description: Download a previously uploaded file
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - file_id
              properties:
                file_id:
                  type: string
                  description: File identifier from upload
      responses:
        "200":
          description: File content
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  filename:
                    type: string
                  content:
                    type: string
                    description: Base64-encoded file content
                  content_type:
                    type: string
                  size:
                    type: integer

  /csv/parse:
    post:
      operationId: ParseCSV
      summary: Parse CSV data
      description: Parse CSV content and return structured data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  description: CSV content (raw text or base64)
                delimiter:
                  type: string
                  description: Field delimiter
                  default: ","
                  maxLength: 1
                has_header:
                  type: boolean
                  description: Whether first row is header
                  default: true
                encoding:
                  type: string
                  description: Input encoding
                  default: utf-8
                max_rows:
                  type: integer
                  description: Maximum rows to parse
                  default: 10000
      responses:
        "200":
          description: Parsed CSV data
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  headers:
                    type: array
                    items:
                      type: string
                  rows:
                    type: array
                    items:
                      type: object
                      additionalProperties: true
                  row_count:
                    type: integer
                  column_count:
                    type: integer

  /csv/generate:
    post:
      operationId: GenerateCSV
      summary: Generate CSV from data
      description: Convert structured data to CSV format
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - data
              properties:
                data:
                  type: array
                  description: Array of objects to convert
                  items:
                    type: object
                    additionalProperties: true
                headers:
                  type: array
                  description: Column headers (optional, inferred from data)
                  items:
                    type: string
                delimiter:
                  type: string
                  default: ","
                include_header:
                  type: boolean
                  default: true
      responses:
        "200":
          description: Generated CSV
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  content:
                    type: string
                    description: CSV content
                  row_count:
                    type: integer

  /excel/read:
    post:
      operationId: ReadExcel
      summary: Read Excel file
      description: Read data from an Excel file
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  description: Base64-encoded Excel file content
                sheet:
                  type: string
                  description: Sheet name to read (default first sheet)
                range:
                  type: string
                  description: Cell range to read (e.g., "A1:D100")
                has_header:
                  type: boolean
                  default: true
      responses:
        "200":
          description: Excel data
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  sheets:
                    type: array
                    items:
                      type: string
                  headers:
                    type: array
                    items:
                      type: string
                  rows:
                    type: array
                    items:
                      type: object
                      additionalProperties: true
                  row_count:
                    type: integer

  /excel/write:
    post:
      operationId: WriteExcel
      summary: Create Excel file
      description: Create an Excel file from structured data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - data
              properties:
                data:
                  type: array
                  description: Array of objects to write
                  items:
                    type: object
                    additionalProperties: true
                sheet_name:
                  type: string
                  description: Name of the sheet
                  default: Sheet1
                headers:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: Generated Excel file
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  content:
                    type: string
                    description: Base64-encoded Excel file
                  filename:
                    type: string

  /convert:
    post:
      operationId: ConvertFormat
      summary: Convert file format
      description: Convert between supported file formats
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
                - target_format
              properties:
                content:
                  type: string
                  description: Source content (base64 for binary, raw for text)
                source_format:
                  type: string
                  description: Source format (auto-detected if not specified)
                  enum:
                    - csv
                    - json
                    - xlsx
                    - xml
                    - yaml
                target_format:
                  type: string
                  description: Target format
                  enum:
                    - csv
                    - json
                    - xlsx
                    - xml
                    - yaml
      responses:
        "200":
          description: Converted content
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  content:
                    type: string
                    description: Converted content
                  source_format:
                    type: string
                  target_format:
                    type: string

components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-API-Key
      description: LeForge API Key

security:
  - ApiKey: []
