openapi: "3.0.0"
info:
  title: LeForge LLM Service
  description: AI-powered text generation, chat completion, classification, summarization, and embeddings
  version: "2.0.0"
  contact:
    name: LeForge Team

servers:
  - url: https://{instance}/api/v1
    variables:
      instance:
        default: api.LeForge.io
        description: LeForge instance URL

paths:
  /chat:
    post:
      operationId: Chat
      summary: Chat with AI
      description: Send a message to the AI and receive a response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
                  description: The user message to send
                  maxLength: 32000
                system_prompt:
                  type: string
                  description: System instructions for the AI
                  maxLength: 4000
                max_tokens:
                  type: integer
                  description: Maximum tokens in response
                  default: 512
                  minimum: 1
                  maximum: 4096
                temperature:
                  type: number
                  description: Creativity level (0-2)
                  default: 0.7
                  minimum: 0
                  maximum: 2
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  response:
                    type: string
                    description: AI response text
                  tokens_used:
                    type: integer
                    description: Total tokens consumed

  /generate:
    post:
      operationId: GenerateText
      summary: Generate text from prompt
      description: Generate text completion from a given prompt
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - prompt
              properties:
                prompt:
                  type: string
                  description: The prompt to complete
                  maxLength: 32000
                max_tokens:
                  type: integer
                  default: 512
                temperature:
                  type: number
                  default: 0.7
      responses:
        "200":
          description: Successful generation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  text:
                    type: string
                    description: Generated text
                  tokens_used:
                    type: integer

  /classify:
    post:
      operationId: ClassifyText
      summary: Classify text into categories
      description: Classify text into one of the provided categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - text
                - categories
              properties:
                text:
                  type: string
                  description: Text to classify
                  maxLength: 32000
                categories:
                  type: array
                  description: List of possible categories
                  items:
                    type: string
                  minItems: 2
                  maxItems: 50
      responses:
        "200":
          description: Successful classification
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  category:
                    type: string
                    description: Predicted category
                  confidence:
                    type: number
                    description: Confidence score 0-1

  /summarize:
    post:
      operationId: SummarizeText
      summary: Summarize text
      description: Generate a summary of the provided text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - text
              properties:
                text:
                  type: string
                  description: Text to summarize
                  minLength: 50
                  maxLength: 100000
                max_length:
                  type: integer
                  description: Maximum summary length in tokens
                  default: 150
                style:
                  type: string
                  description: Summary style
                  enum:
                    - bullet
                    - paragraph
                    - tldr
                  default: paragraph
      responses:
        "200":
          description: Successful summarization
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  summary:
                    type: string
                    description: Generated summary
                  compression_ratio:
                    type: number

  /extract-entities:
    post:
      operationId: ExtractEntities
      summary: Extract entities from text
      description: Extract named entities like people, organizations, dates, etc.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - text
              properties:
                text:
                  type: string
                  description: Text to extract entities from
                  maxLength: 32000
                entity_types:
                  type: array
                  description: Types of entities to extract (empty for all)
                  items:
                    type: string
      responses:
        "200":
          description: Successful extraction
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  entities:
                    type: array
                    items:
                      type: object
                      properties:
                        text:
                          type: string
                        type:
                          type: string
                        confidence:
                          type: number

  /embeddings:
    post:
      operationId: GenerateEmbeddings
      summary: Generate text embeddings
      description: Generate vector embeddings for semantic search and similarity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - text
              properties:
                text:
                  type: string
                  description: Text to generate embeddings for
                  maxLength: 8000
      responses:
        "200":
          description: Successful embedding generation
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  embeddings:
                    type: array
                    items:
                      type: number
                  dimensions:
                    type: integer

components:
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-API-Key
      description: LeForge API Key

security:
  - ApiKey: []
